### ISSUE TITLE
Send does not work

### ISSUE THREAD

**Issue by CamperS7** [ShiryaevAnton/Isc.CrestronTelegram#1]
Hi,
I cant send messsages from the crestron debugger to telegram.
Sending vom Telegram to Crestron works fine. 

i installed the program on a cp4, started a new bot on telegram and copied the apI key to the simpl.plus module.

Thanks

Michael

**Comment by ShiryaevAnton** [comment]
You have to register yourself to send messages from the debugger.

To register you need to send the word "register" to the chatbot. You will get a response from chatbot [YOUR_NAME] thank you for registering. 

To unregister you need to send the word "unregister". 

Probably I choose the wrong names. The better words would be "subscribe" and "unsubscribe". You need to subscribe to get messages from crestron

**Comment by CamperS7** [comment]
Hi

 

Thank you very much. That´s it.

 

Michael

 

 

 

Von: ShiryaevAnton ***@***.***> 
Gesendet: Samstag, 4. Mai 2024 08:32
An: ShiryaevAnton/Isc.CrestronTelegram ***@***.***>
Cc: CamperS7 ***@***.***>; Author ***@***.***>
Betreff: Re: [ShiryaevAnton/Isc.CrestronTelegram] Send does not work (Issue #1)

 

You have to register yourself to send messages from the debugger.

To register you need to send the word "register" to the chatbot. You will get a response from chatbot [YOUR_NAME] thank you for registering.

To unregister you need to send the word "unregister".
